### ISSUE TITLE
what is the typical use case for this smart contract spider?

### ISSUE THREAD

**Issue by rayeaster** [xf97/HuangGai#2]
looks like a smart contract search engine?

**Comment by xf97** [comment]
contractSpider is used to obtain the smart contract source code and its deployment address. It is implemented using the scrapy framework. The target crawling website is etherscan.io (in China, the target website is changed to cn.etherscan.com). After ensuring that your device has the scrapy framework installed (and cloning this project to the local), you can start the crawler by typing the following commands in the terminal:
`scrapy crawl getContractAddressSpider`
`scrapy crawl nontokenContractAddress`
`scrapy crawl codeGetter`
The above three instructions will get the addresses of 1,000 ERC20 contracts and 10,000 open-source contracts (stored in the data folder) and the source code of all contracts (stored in the sourceCode folder, use the contract address to name each source code file). To prevent local ip from being blocked, we set the download interval to 5 seconds, which makes the entire crawling process last for more than ten hours. You can adjust the download speed by setting the download interval in the setting.py file.
As our research project is still in progress, after the research is over, we will fully describe the possible usages of this project.

**Comment by xf97** [comment]
@rayeaster Closed.
