### ISSUE TITLE
无法注入重入漏洞

### ISSUE THREAD

**Issue by 850tomato** [xf97/HuangGai#4]
您好，感谢您的工作。我们在运行时发现它似乎无法进行重入漏洞的注入。其余的漏洞都可以正常生成在dataset路径里。但在进行重入漏洞时，dataset路径里没有任何文件，而且整个过程中没有报错，在显示的结果中，SuccessContractsNums的数量和在userNeeds里设置的相同，但文件夹里就是没有文件。期待您的回复。

**Comment by xf97** [comment]
你好，很抱歉这个工作目前已经不在我的维护范围，并且当前我手边也缺乏相应的环境来复现你的问题。不过，根据你描述的情况，能否依次确定如下几点: 1) 黄盖生成的注入合约的存储路径是否已经被创建。2) 如果生成包含其他种类bug的注入合约，是否也存在此情况。3) 是否已经准备了真实合约。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月13日(周四) 下午2:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xf97/HuangGai] 无法注入重入漏洞 (Issue #4)




 
您好，感谢您的工作。我们在运行时发现它似乎无法进行重入漏洞的注入。其余的漏洞都可以正常生成在dataset路径里。但在进行重入漏洞时，dataset路径里没有任何文件，而且整个过程中没有报错，在显示的结果中，SuccessContractsNums的数量和在userNeeds里设置的相同，但文件夹里就是没有文件。期待您的回复。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 850tomato** [comment]
您好，感谢您的回复。我检测了上面3个条件，都是满足的。而且别的bug种类是可以生成的，只有重入漏洞不行。请问，在您之前的测试中，是可以在该存储路径中正常生成吗？   您用一台linux系统，并按照您给出的3个步骤，应该就可以复现该问题，我使用的是您给的sourceCode默认的合约。

**Comment by xf97** [comment]
你好，我现在放假了，缺乏设备，同时我已经不再此篇工作了，我的猜想是后续对重入bug的代码修改触发了异常，你可否手动修改重入bug的代码以检查具体的异常，应该不会是大问题。

**Comment by 850tomato** [comment]
您好，感谢您的回复。请问，在之前的版本中，重入漏洞是可以正常生成的吗？我是否可以使用之前的代码生成重入漏洞。

**Comment by xf97** [comment]
嗯对，要不我实验怎么做的（捂脸笑）。不过我现在要毕业了，导师把这篇工作移交其他人了，所以我就不再跟进这个工具了。感谢你的这个工作的关注，希望能帮助到你的研究。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月22日(星期六) 下午3:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [xf97/HuangGai] 无法注入重入漏洞 (Issue #4)





 
您好，感谢您的回复。请问，在之前的版本中，重入漏洞是可以正常生成的吗？我是否可以使用之前的代码生成重入漏洞。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 850tomato** [comment]
感谢您的帮助，祝您学业和工作顺利。

**Comment by 850tomato** [comment]
您好，请问大约哪个版本可以正常注入重入漏洞，我使用原来的版本试一下？
